#!/usr/bin/env bash

#set -o xtrace
set -o errexit
set -o pipefail
set -o nounset

bin="$(cd "$(dirname "$0")" > /dev/null; pwd)"
home="$(cd "$bin/../.." > /dev/null; pwd)" # this script lives in .build/sh

# Switch to the project root so all commands work properly
cd "$home"

usage() {
  if [[ $# -gt 0 ]]; then
    echo "$*" 1>&2
  fi
  cat <<EOF
Usage: $(basename "$0") [class name] (option)*

Options:
EOF
  exit 1
}

_main() {
  local class_name=""
  fresh_build=true
  while [[ "$#" -gt 0 ]]; do
    case "$1" in
      --reuse)
        fresh_build=false
        shift
        ;;
      -h|--help)
        usage
        shift
        ;;
      *)
        if [[ -z "${class_name:-}" ]]; then
          class_name="$1"
          shift
        else
          usage "Unknown argument $1"
        fi
        ;;
    esac
  done

  if [[ -z "${class_name:-}" ]]; then
    usage "No class provided"
  fi

  path="$(echo "$class_name" | tr '.' '/' ).java"
  #prefix="$( find test | grep "$path" | awk -F/ '{print $2}' )"

  if $fresh_build; then
    if [[ ! "$path" =~ distributed/upgrade ]]; then
      ant realclean && ant && ant generate-idea-files
    fi
  fi

  #test_timeout=$(grep "name=\"test.$prefix.timeout\"" build.xml | awk -F'"' '{print $4}' || true)
  #if [ -z "$test_timeout" ]; then
  #  test_timeout=$(grep 'name="test.timeout"' build.xml | awk -F'"' '{print $4}')
  #fi

  counter=1
  echo ">>> Running attempt $counter"
  while $bin/ci-test "$class_name" --reuse; do
    counter=$(( $counter + 1 ))
    echo ">>> Running attempt $counter"
  done;
  echo "Exited after $counter attempts"
}

_main "$@"
